---2017-6-3 12:46:52【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:53【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:53【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 12:46:55【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 13:6:52【Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at Object.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\apimain.js:92:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: connect EHOSTUNREACH 192.168.0.103:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-6-3 16:43:36【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:36【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:36【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:37【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:37【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:37【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:37【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:37【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:37【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-6-3 16:43:37【Error: Connection terminated
    at Connection.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (F:\items\zyd_share\zyd_share\fgs_Manager（正式）\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
